/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   ArcScrollThreshold.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, css, LitElement} from 'lit-element';

import {ArcScrollTargetMixin} from '@advanced-rest-client/arc-scroll-target-mixin';

declare namespace UiElements {

  /**
   * A port of `iron-scroll-threshold` element.
   */
  class ArcScrollThreshold {

    /**
     * Read-only value that tracks the triggered state of the upper threshold.
     */
    readonly upperTriggered: Boolean|null;

    /**
     * Read-only value that tracks the triggered state of the lower threshold.
     */
    readonly lowerTriggered: Boolean|null;
    _upperTriggered: any;
    _lowerTriggered: any;

    /**
     * True if the orientation of the scroller is horizontal.
     */
    horizontal: boolean|null|undefined;
    readonly _defaultScrollTarget: any;
    _scrollDebouncer: any;
    onlowerthreshold: Function|null|undefined;
    onupperthreshold: Function|null|undefined;

    /**
     * Distance from the top (or left, for horizontal) bound of the scroller
     * where the "upper trigger" will fire.
     */
    upperThreshold: number|null|undefined;

    /**
     * Distance from the bottom (or right, for horizontal) bound of the scroller
     * where the "lower trigger" will fire.
     */
    lowerThreshold: number|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    render(): any;
    _scrollTargetChanged(value: any): void;
    _setOverflow(scrollTarget: any): void;
    _scrollHandler(): void;
    _initCheck(): void;

    /**
     * Checks the scroll thresholds.
     * This method is automatically called by iron-scroll-threshold.
     */
    checkScrollThresholds(): void;

    /**
     * Clear the upper and lower threshold states.
     */
    clearTriggers(): void;
  }
}
